easy_admin:
  list:
    actions:
      - { name: "edit", icon: "pencil", label: false, css_class: "btn btn-secondary"}
      - { name: "delete", icon: "trash", label: false, css_class: "btn btn-danger"}
